### ISSUE TITLE
hello, deploy issue

### ISSUE THREAD

**Issue by lbmili2018** [camenduru/ml-mgie-hf#1]
![20240208-115456](https://github.com/camenduru/ml-mgie-hf/assets/34003245/05dd4619-f3a1-4eea-85e5-36a1211e6f7f)
After deployment, inference is error ,  is there a problem with the installation package?   eg, cuda?  transformers?

Here is the output, occur many errors about weights not used:
![20240208-115824](https://github.com/camenduru/ml-mgie-hf/assets/34003245/c3f4a606-68a1-4dcd-8101-2b2e6145404b)
![1](https://github.com/camenduru/ml-mgie-hf/assets/34003245/126ed15a-ca3e-44a1-863c-936d8fd354e9)
![2](https://github.com/camenduru/ml-mgie-hf/assets/34003245/ccad3e39-472d-4f1c-a734-09d76b7899a0)

**Comment by camenduru** [comment]
Please try with those models https://huggingface.co/camenduru/pytorch_mgie/tree/main

**Comment by lbmili2018** [comment]
thanks bro, it's works !!!

**Comment by hjShin0** [comment]
Hello, thank you so much for your work. Did you finetuned your model again? Your new model works well with the repo codes but original LLaVA doesn't.
